# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'aracqr' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for aracqr
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'RNShare', :path => '../node_modules/react-native-share'

  target 'aracqrTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'aracqr-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for aracqr-tvOS

  target 'aracqr-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
